#! /bin/bash

# Ensure arguments were passed and validate them
if [ ! $1 ]; then
	echo "No wallpaper specified"
	exit
fi
if [ ! -f $1 ]; then
	echo "Path not valid"
	exit
fi
if [[ $2 && "wal --backend | grep $2" ]]; then
	BACKEND=true
	echo "> Backend specified: $2"
else
	BACKEND=false
	echo "> No backend specified"
fi

# Change bg
while [ true ]
do
	echo "System wallpaper will be replaced. Make sure the original wallpaper is backed up somewhere else. Continue? [Y/N]"
	read -p ">" confirm
	if [[ $confirm == "y" || $confirm == "Y" ]]; then
		echo "Changing wallpaper..."
		break
	elif [[ $confirm == "n" || $confirm == "N" ]]; then
		echo "Exiting..."
		exit
	else
		echo "Not a valid option"
	fi
done

sudo cp "$1" /usr/share/backgrounds/main_wp
killall hyprpaper
hyprpaper &

sleep 0.5

# Generate theme
if [ $BACKEND == true ]; then
	wal -i /usr/share/backgrounds/main_wp --contrast 1.5 --saturate 0.85 --fg '#efefef' --backend "$2"
else
	wal -i /usr/share/backgrounds/main_wp --contrast 1.5 --saturate 0.85 --fg '#efefef'
fi

# Config folders
WAL_CACHE="$HOME/.cache/wal"
KITTY_CFG="$HOME/.config/kitty"
HYPR_CFG="$HOME/.config/hypr"
SUPERFILE_CFG="$HOME/.config/superfile/theme"
WAYBAR_CFG="$HOME/.config/waybar"
ROFI_CFG="$HOME/.config/rofi"
DUNST_CFG="$HOME/.config/dunst"
WLOGOUT_CFG="$HOME/.config/wlogout"
VESKTOP_CFG="$HOME/.config/vesktop/themes"
EWW_CFG="$HOME/.config/eww"
HOMEPAGE_CFG="$HOME/.config/homepage"

# Exit if not WAL_CACHE
if [ ! -d "$WAL_CACHE" ]; then
	echo "Wal-cache not present. Exiting."
	exit
fi

# Move config themes to respective folders
# --== KITTY ==--
if [ ! -d "$KITTY_CFG" ]; then
	mkdir -p "$KITTY_CFG"
fi
cp "$WAL_CACHE/colors-kitty.conf" "$KITTY_CFG/"

# --== HYPRLAND ==-- 
if [ ! -d "$HYPR_CFG" ]; then
	mkdir -p "$HYPR_CFG"
fi
cp "$WAL_CACHE/colors-hyprland.conf" "$HYPR_CFG/"

# --== SUPERFILE ==--
if [ ! -d "$SUPERFILE_CFG" ]; then
	mkdir -p "$SUPERFILE_CFG"
fi
if [ -f "/bin/create_superfile_toml" ]; then
	create_superfile_toml
fi

# --== STARSHIP PROMPT ==--
if [ -f "/bin/create_starship_toml" ]; then
	create_starship_toml
fi

# --== WAYBAR ==--
if [ ! -d "$WAYBAR_CFG" ]; then
	mkdir -p "$WAYBAR_CFG"
fi
cp "$WAL_CACHE/colors-waybar.css" "$WAYBAR_CFG/colors-waybar.css"
killall waybar
nohup waybar > /dev/null 2>&1 &

# --== SDDM ==--
if [ -f "/bin/create_sddm_colors" ]; then
	sudo create_sddm_colors
fi

# --== ROFI ==--
if [ ! -d "$ROFI_CFG" ]; then
	rofi dump-config > "$ROFI_CFG/config.rasi" -p
	echo '@theme "rofi-custom"' >> "$ROFI_CFG/config.rasi"
fi
if [ -f "/bin/create_rofi_theme" ]; then
	create_rofi_theme
fi

# --== DUNST ==--
if [ ! -d "$DUNST_CFG" ]; then
	mkdir -p "$DUNST_CFG"
fi
if [ -f "/bin/create_dunstrc" ]; then
	create_dunstrc
	killall dunst
	nohup dunst > /dev/null 2>&1 &
fi

# --== WLOGOUT ==--
if [ ! -d "$WLOGOUT_CFG" ]; then
	if [ -d "/etc/wlogout" ]; then
		echo "Copying wlogout default config"
		cp -r "/etc/wlogout" "$HOME/.config/"
	else
		echo "wlogout default config not found"
	fi
fi
if [ -d "$WLOGOUT_CFG" ]; then
	cp "$WAL_CACHE/colors-waybar.css" "$WLOGOUT_CFG/colors.css"
fi

# --== VESKTOP ==--
if [ -d "$VESKTOP_CFG" ]; then
  cp "$WAL_CACHE/colors.css" "$VESKTOP_CFG/colors.css"
fi

# --== EWW ==--
if [ -d "$EWW_CFG" ]; then
	cp "$WAL_CACHE/colors-waybar.css" "$EWW_CFG/colors.css"
fi

# --== HOMEPAGE ==--
if [ -d "$HOMEPAGE_CFG" ]; then
  cp "$WAL_CACHE/colors.css" "$HOMEPAGE_CFG/colors.css"
fi
