[General]
background=WP.png
profilePicture=PF.png
username=karch

[Design]
primaryColor=#efefef
backgroundColor=rgba(0,0,0,0.45)
borderColor=rgba(255,255,255,0.75)
errorColor=#ff0000
fontFamily=JetBrains Mono

[Behavior]
showSessionCombo=false
autoFocus=true
hideErrorDelay=3000