#! /bin/bash

# Ensure argument was passed + path valid
if [ ! $1 ]; then
	echo "No wallpaper specified"
	exit
fi
if [ ! -f $1 ]; then
	echo "Path not valid"
	exit
fi

# Change bg
while [ true ]
do
	echo "System wallpaper will be replaced. Make sure the original wallpaper is backed up somewhere else. Continue? [Y/N]"
	read -p ">" confirm
	if [[ $confirm == "y" || $confirm == "Y" ]]; then
		echo "Changing wallpaper..."
		break
	elif [[ $confirm == "n" || $confirm == "N" ]]; then
		echo "Exiting..."
		exit
	else
		echo "Not a valid option"
	fi
done

sudo cp $1 /usr/share/backgrounds/main_wp
killall hyprpaper
hyprpaper &

# Generate theme
wal -i /usr/share/backgrounds/main_wp --contrast 1.5 --saturate 0.85 --fg '#efefef'

# Config folders
WAL_CACHE="$HOME/.cache/wal"
KITTY_CFG="$HOME/.config/kitty"
HYPR_CFG="$HOME/.config/hypr"
SUPERFILE_CFG="$HOME/.config/superfile/theme"
STARSHIP_CFG="$HOME/.config/starship.toml"
WAYBAR_CFG="$HOME/.config/waybar"
ROFI_CFG="$HOME/.config/rofi"
DUNST_CFG="$HOME/.config/dunst"

# Exit if not WAL_CACHE
if [ ! -d "$WAL_CACHE" ]; then
	echo "Wal-cache not present. Exiting."
	exit
fi

# Move config themes to respective folders
# --== KITTY ==--
if [ ! -d "$KITTY_CFG" ]; then
	mkdir -p "$KITTY_CFG"
fi
cp "$WAL_CACHE/colors-kitty.conf" "$KITTY_CFG/"

# --== HYPRLAND ==-- 
if [ ! -d "$HYPR_CFG" ]; then
	mkdir -p "$HYPR_CFG"
fi
cp "$WAL_CACHE/colors-hyprland.conf" "$HYPR_CFG/"

# --== SUPERFILE ==--
if [ ! -d "$SUPERFILE_CFG" ]; then
	mkdir -p "$SUPERFILE_CFG"
fi
if [ -f "/bin/create_superfile_toml" ]; then
	create_superfile_toml
fi

# --== STARSHIP PROMPT ==--
if [ -f "/bin/create_starship_toml" ]; then
	create_starship_toml
fi

# --== WAYBAR ==--
if [ ! -d "$WAYBAR_CFG" ]; then
	mkdir -p "$WAYBAR_CFG"
fi
cp "$WAL_CACHE/colors-waybar.css" "$WAYBAR_CFG/colors-waybar.css"
killall waybar
waybar &

# --== SDDM ==--
if [ -f "/bin/create_sddm_colors" ]; then
	sudo create_sddm_colors
fi

# --== ROFI ==--
if [ ! -d $ROFI_CFG ]; then
	rofi dump-config > "$ROFI_CFG/config.rasi" -p
	echo '@theme "rofi-custom"' >> "$ROFI_CFG/config.rasi"
fi
if [ -f "/bin/create_rofi_theme" ]; then
	create_rofi_theme
fi

# --== DUNST ==--
if [ ! -d $DUNST_CFG ]; then
	mkdir -p $DUNST_CFG
fi
if [ -f "/bin/create_dunstrc" ]; then
	create_dunstrc
	killall dunst
	dunst
fi








