#! /usr/bin/python3

import os
from pathlib import Path

def main():
    COLORS_PATH = f"/home/karch/.cache/wal/colors"
    SDDM_PATH = "/usr/share/sddm/themes/karch"

    if not (os.path.exists(COLORS_PATH) and os.path.exists(SDDM_PATH)):
        print(COLORS_PATH, SDDM_PATH)
        return

    with open(COLORS_PATH, mode="r", encoding="utf-8") as f:
        color = f.readlines()
    for idx in range(0, len(color)):
        color[idx] = color[idx][:-1]

    colors_js = ""
    for idx in range(0, len(color)):
        colors_js += f"var color{idx} = '{color[idx] if idx != 0 else '#b0'+color[idx].replace("#", "")}'\n"

    if os.path.exists(f"{SDDM_PATH}/colors.js"):
        os.remove(f"{SDDM_PATH}/colors.js")
    with open(f"{SDDM_PATH}/colors.js", mode="x", encoding="utf-8") as f:
        f.write(colors_js)

    print("Created sddm colors")
    return

if __name__=="__main__":
    main()
