#! /usr/bin/python3
import os
from pathlib import Path

def main():
    WAL_PATH = f"{Path.home()}/.cache/wal/colors"
    ROFI_PATH = f"{Path.home()}/.config/rofi"

    if not (os.path.exists(WAL_PATH) and os.path.exists(ROFI_PATH)):
        print("WAL/ROFI path does not exist.")
        return
    with open(WAL_PATH, mode="r", encoding="utf-8") as f:
        color = f.readlines()
    for idx in range(len(color)):
        color[idx] = color[idx][:-1]

    ROFI_VARS = \
f'''
* {"{"}
	main-bg: {color[0]}d8;
	select-bg: {color[7]}a8;
	foreground: {color[15]};
	border: {color[6]};
{"}"}
'''

    ROFI_THEME = ROFI_VARS + \
'''
window {
	background-color: @main-bg;
	
	border: 3px;
	border-radius: 5px;
	border-color: @border;
	
	padding: 10px;

	width: 25em;
	height: 15em;
}



mainbox {
	border: 0;
	padding: 0;
	background-color: transparent;
}



inputbar {
	text-color: @foreground;
	background-color: transparent;
	
	padding: 3px;

	max-width: 5em;
}
case-indicator {
	enabled: false;
}
prompt {
	enabled: false;
}
entry {
	background-color: transparent;

	font: "JetBrains Mono NerdFont bold 14";
	text-color: @foreground;

	border: 3px;
	border-color: @border;
	border-radius: 5px;

	margin: 0 5px;

	padding: 5px 2px;

	margin: 0 6em;
}
textbox-current-entry {
	enabled: false;
}
icon-current-entry {
	enabled: false;
}



listview {
	background-color: transparent;
	padding: 0.5em 2em;

	spacing: 5px;
}
element {
	background-color: transparent;

	padding: 5px;
}
element selected{
	background-color: @select-bg;

	border: 3px;
	border-color: @border;
	border-radius: 5px;
}
element-icon {
	background-color: transparent;
	margin-left: 10px;

	size: 1.25em;
}
element-index {
	enabled: false;
}
element-text {
	background-color: transparent;
	text-color: @foreground;
	font: "JetBrains Mono NerdFont bold 16";
}
element-text.active {
	background-color: #ff0000;
}
'''

    ROFI_THEME_PATH = ROFI_PATH + "/rofi-custom.rasinc"
    if os.path.exists(ROFI_THEME_PATH):
        os.remove(ROFI_THEME_PATH)
    
    with open(ROFI_THEME_PATH, mode="x", encoding="utf8") as f:
        f.write(ROFI_THEME)

    print("Created ROFI theme")
    return

if __name__ == "__main__":
    main()
